# Generated by Django 5.2.4 on 2025-07-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=101)),
                ('description', models.TextField()),
                ('formattedViews', models.IntegerField()),
                ('lengthh', models.CharField(max_length=20)),
                ('pubdate', models.DateField()),
                ('channel_name', models.CharField(max_length=1000)),
            ],
        ),
    ]
