# Generated by Django 5.2.4 on 2025-07-08 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='lengthh',
            new_name='length',
        ),
    ]
