# Generated by Django 5.2.4 on 2025-07-08 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0002_rename_lengthh_video_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='length',
            new_name='lengthh',
        ),
    ]
