# Generated by Django 5.2.4 on 2025-07-08 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0003_rename_length_video_lengthh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='formattedViews',
            new_name='unformattedViews',
        ),
    ]
