# Generated by Django 5.2.4 on 2025-07-08 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0004_rename_formattedviews_video_unformattedviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='unformattedViews',
            new_name='Views',
        ),
    ]
