# Generated by Django 5.2.4 on 2025-07-09 10:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0005_rename_unformattedviews_video_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='reqdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
