# Generated by Django 5.2.4 on 2025-07-09 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0006_video_reqdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='reqdate',
            new_name='requestdate',
        ),
    ]
