# Generated by Django 5.2.4 on 2025-07-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0008_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='title',
            field=models.CharField(default='Request', max_length=101),
            preserve_default=False,
        ),
    ]
