# Generated by Django 5.2.4 on 2025-07-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0009_request_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='channel_name',
            field=models.CharField(default='null', max_length=1000),
            preserve_default=False,
        ),
    ]
