# Generated by Django 5.2.4 on 2025-07-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0010_request_channel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='stringdate',
            field=models.CharField(default='date', max_length=1000),
            preserve_default=False,
        ),
    ]
