# Generated by Django 5.2.4 on 2025-07-23 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0011_request_stringdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='keys',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='downloader.video'),
        ),
        migrations.AddField(
            model_name='video',
            name='requests',
            field=models.IntegerField(default=0),
        ),
    ]
