# Generated by Django 5.2.4 on 2025-07-23 10:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0012_request_keys_video_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='timereq',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
