# Generated by Django 5.2.4 on 2025-07-23 10:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0013_request_timereq'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='timereq',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
