# Generated by Django 5.2.4 on 2025-07-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0014_video_timereq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='timereq',
        ),
        migrations.AlterField(
            model_name='request',
            name='timereq',
            field=models.CharField(max_length=20),
        ),
    ]
