# Generated by Django 5.2.4 on 2025-07-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0019_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='quality',
            name='resolution',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
