# Generated by Django 5.2.4 on 2025-07-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0020_quality_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='quality',
            name='qual',
            field=models.CharField(default='EMPTY', max_length=100),
            preserve_default=False,
        ),
    ]
