# Generated by Django 5.2.4 on 2025-07-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0021_quality_qual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality',
            name='qual',
            field=models.JSONField(default=list),
        ),
    ]
